# Generated by Django 5.2.6 on 2025-10-12 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='submited_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
