# Generated by Django 5.2.6 on 2025-10-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_submited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
