# Generated by Django 5.2.6 on 2025-10-15 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_highest_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
